In [1]:
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
training_data = pd.read_csv('training_data.csv', header=0)

In [18]:
print(len(training_data))

1223


In [4]:
row1 = training_data.head(1)

In [5]:
nrow1 = row1.values
print(row1)
print(nrow1[0])

       63.75  63.849998  63.049999  63.150002
0  63.650002       64.0  63.400002  63.900002
[63.650002 64.       63.400002 63.900002]


In [19]:
data = training_data.values

In [20]:
print(data[0])
print(data[1])

[63.650002 64.       63.400002 63.900002]
[64.5      65.150002 64.5      65.      ]


In [21]:
print(training_data.columns)

Index(['63.75', '63.849998', '63.049999', '63.150002'], dtype='object')


In [22]:
ind = training_data.columns.values

In [23]:
print(ind)
print(ind[0])

['63.75' '63.849998' '63.049999' '63.150002']
63.75


In [36]:
testing_data = pd.read_csv('testing_data.csv', header=0)
testDataR1 = testing_data.columns.values
testData = testing_data.values

ftestDataR1 = testDataR1.astype(float)
ftestData = testData.astype(float)

In [25]:
print(testDataR1)
print(testData[0])

['104.449997' '105.199997' '104.25' '104.949997']
[106.550003 107.       106.349998 106.550003]


In [26]:
print(testDataR1[0] == testDataR1[3])

False


In [59]:
import csv
count = 0
dn = 0
delta = 0.005
with open('output.csv',"w", encoding='utf-8' ,newline='') as csvfile:
    writer = csv.writer(csvfile)
    if ((ftestDataR1[3] - ftestDataR1[0])/ftestDataR1[3]) > delta :
        if count < 1 :
            writer.writerows('1')
            count +=1
    elif ((ftestDataR1[0] - ftestDataR1[3])/ftestDataR1[3]) > delta :
        if count >= 0 :
            writer.writerow([-1])
            count -=1
    else :
        writer.writerows('0')

    for row in testData :
        if ((ftestData[dn][3] - ftestData[dn][0])/ftestData[dn][3]) > delta :
            if count < 1 :
                writer.writerows('1')
                count +=1
            else :
                writer.writerows('0')
        elif ((ftestData[dn][0] - ftestData[dn][3])/ftestData[dn][3]) > delta :
            if count >= 0 :
                writer.writerow([-1])
                count -=1
            else :
                writer.writerows('0')
        else :
            writer.writerows('0')

        dn+=1
 
